Repository OpenCodeChicago/hacktoberfest-2025-frontend, pull requests merged in 2025-10, with the labels that each got.

#17 feat: include docker env
  .dockerignore
  Dockerfile
Labels: hacktoberfest, hacktoberfest-2025, hacktoberfest-accepted

#20 feat: add return page component
  src/pages/Return/Return.jsx
Labels: frontend, hacktoberfest, hacktoberfest-2025, hacktoberfest-accepted

#24 feat: add "About CoreX" page (#24)
  package-lock.json
  src/pages/About/About.jsx
  src/routes/RouterConfig.jsx
Labels: frontend, hacktoberfest, hacktoberfest-2025, hacktoberfest-accepted

#28 Developed the TopFooter
  public/images/facebook_icon.png
  public/images/linkedin_icon.png
  public/images/x_icon.png
  public/images/youtube_icon.png
  src/components/Footer/TopFooter.jsx
  src/components/Footer/index.js
  src/layouts/RootLayout.jsx
Labels: frontend, hacktoberfest, hacktoberfest-2025, hacktoberfest-accepted

#39 feat: implement centralized API services with axios instance and cart…
  src/api/axiosInstance.js
  src/api/cartService.js
  src/api/index.js
  src/api/productService.js
  src/services/api.js
Labels: frontend, hacktoberfest, hacktoberfest-2025, hacktoberfest-accepted, javascript, axios, api

#41 Fix minor fixes in Footer related to UI.
  src/components/Footer/TopFooter.jsx
Labels: frontend, hacktoberfest, hacktoberfest-2025, hacktoberfest-accepted, react, tailwind

#56 Feature/#11 - Added top header and added it the root layout.
  src/components/Header/MainHeader.jsx
  src/components/TopHeader/TopHeader.jsx
  src/components/TopHeader/index.js
  src/layouts/RootLayout.jsx
Labels: frontend, hacktoberfest, hacktoberfest-2025, hacktoberfest-accepted, react, tailwind

#64 .created terms of service page
  src/pages/TermsOfService/TermsOfService.jsx
  src/routes/RouterConfig.jsx
Labels: frontend, good first issue, hacktoberfest, hacktoberfest-2025, hacktoberfest-accepted, react

#72 feat: Enhance ProductCard with animations and improve product display…
  src/components/Products/ProductCard.jsx
  src/index.css
  src/pages/Products/Products.jsx
Labels: frontend, hacktoberfest, hacktoberfest-2025, hacktoberfest-accepted, react, tailwind

#73 feat: Improve cart feedback in ProductCard and clean up CSS variables
  src/components/Products/ProductCard.jsx
  src/index.css
  src/pages/Products/Products.jsx
Labels: frontend, hacktoberfest, hacktoberfest-2025, hacktoberfest-accepted, react

#54 fix: implement-minor-suggestion-for-better-UX
  src/components/Footer/TopFooter.jsx
  src/layouts/RootLayout.jsx
Labels: frontend, hacktoberfest, hacktoberfest-2025, hacktoberfest-accepted, react, tailwind

#75 Update CI badge in README.md
  README.md
Labels: hacktoberfest, hacktoberfest-2025, hacktoberfest-accepted, ci/cd, devops

#76 Update CI/CD badge in README.md
  README.md
Labels: hacktoberfest, hacktoberfest-2025, hacktoberfest-accepted, ci/cd, devops

#77 developed-register-page
  public/images/coreX-logo.svg
  src/index.css
  src/pages/Register.jsx
  src/routes/RouterConfig.jsx
Labels: frontend, hacktoberfest, hacktoberfest-2025, hacktoberfest-accepted, react, tailwind

#79 feat: Add Recently Viewed section and utility functions for managing …
  src/components/Products/ProductCard.jsx
  src/components/RecentlyViewed.jsx
  src/index.css
  src/pages/Products/Products.jsx
  src/utils/recentlyViewed.js
Labels: frontend, hacktoberfest, hacktoberfest-2025, hacktoberfest-accepted, react, tailwind

#82 feat: Add FilterPanel and RangeSlider components for product filtering
  src/components/Products/FilterPanel/Accordion.jsx
  src/components/Products/FilterPanel/FilterPanel.css
  src/components/Products/FilterPanel/FilterPanel.jsx
  src/components/Products/FilterPanel/RangeSlider.jsx
  src/pages/Products/Products.jsx
Labels: frontend, hacktoberfest, hacktoberfest-2025, hacktoberfest-accepted, react, tailwind
